Repository chingu-voyages/v42-bears-team-41, pull requests merged in 2023-01, with the labels that each got.

#15 Setup Next.js Boilerplate
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/task-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .gitignore
  .prettierignore
  .prettierrc.json
  NEXTJS_TEMPLATE_README.md
  README.md
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/pages/_app.js
  src/pages/_document.js
  src/pages/api/hello.js
  src/pages/index.js
  src/styles/Home.module.css
  src/styles/globals.css
Labels: task

#21 homepage welcome msg and button
  src/pages/index.js
Labels: enhancement, task, must_have

#25 [EPIC] Style & Theming Overhaul
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/task-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/workflows/eslint.yml
  .gitpod.yml
  .testing/createSampleStyckerCardData.js
  .testing/generateSampleImageURL.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/Badge/index.jsx
  src/components/DividerArea/index.jsx
  src/components/StyckerCard/index.jsx
  src/components/Theme/ThemeToggle.jsx
  src/components/Theme/state.jsx
  src/config/defaults.config.js
  src/helpers/randomInteger.js
  src/pages/_app.js
  src/pages/explore.jsx
  src/styles/SelectStyle.js
Labels: enhancement
